name: 部署到 GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4

      - name: 配置 Pages
        uses: actions/configure-pages@v5

      - name: 上传静态文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: 发布到 Pages
        uses: actions/deploy-pages@v4
